const $=s=>document.querySelector(s);let companyId=1,user=null,permissions={};let cache={products:[],orders:[],purchases:[],parties:[]};
const api=async(url,opt={})=>{opt.headers={...(opt.headers||{}),'x-company-id':companyId};const r=await fetch(url,opt);const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const money=n=>`Rs. ${Number(n||0).toLocaleString(undefined,{maximumFractionDigits:2})}`;const today=()=>new Date().toISOString().slice(0,10);
const modules=[['Dashboard','📊'],['Sales','🛍️'],['Purchases','🛒'],['Inventory','📦'],['Customers','👥'],['Suppliers','🚚'],['Financing','💳'],['Payments','💰'],['Ledger','📒'],['Reports','📈'],['Import / Export','📥'],['Users & Roles','🔐'],['Settings','⚙️']];
async function boot(){$('#login-btn').onclick=login;$('#login-pass').onkeydown=e=>{if(e.key==='Enter')login()};$('#dark').onchange=e=>document.body.classList.toggle('dark',e.target.checked);$('#close').onclick=()=>$('#modal').hidden=true;$('#date').textContent=new Date().toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'});const lb=$('#logout-btn');if(lb)lb.onclick=()=>{localStorage.removeItem('nexusSession');location.reload()};const saved=localStorage.getItem('nexusSession');if(saved){try{const s=JSON.parse(saved);companyId=s.companyId;user=s.user;permissions=s.permissions;const cs=await fetch('/api/my-companies?username='+encodeURIComponent(user.username)).then(r=>r.json());$('#company-select').innerHTML=cs.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');$('#company-select').value=String(companyId);$('#who').textContent=user.displayName;$('#role').textContent=user.role;$('#login').hidden=true;$('#app').hidden=false;renderNav();show('Dashboard');return}catch(e){localStorage.removeItem('nexusSession')}}companyId=0}
async function login(){try{const companyName=($('#login-company').value||'').trim();const d=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('#login-user').value,password:$('#login-pass').value,companyName})}).then(async r=>{const x=await r.json();if(!r.ok)throw Error(x.error);return x});companyId=d.company.id;user=d.user;permissions=d.permissions;localStorage.setItem('nexusSession',JSON.stringify({companyId,user,permissions}));const cs=await fetch('/api/my-companies?username='+encodeURIComponent(user.username)).then(r=>r.json());$('#company-select').innerHTML=cs.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');$('#company-select').value=String(companyId);$('#who').textContent=user.displayName;$('#role').textContent=user.role;$('#login').hidden=true;$('#app').hidden=false;renderNav();show('Dashboard')}catch(e){alert(e.message)}}
function can(m){return user?.role==='Super Admin'||permissions[m]!==false}function renderNav(){const nav=$('#nav');nav.innerHTML=modules.filter(x=>can(x[0])).map(x=>`<a class="nav-item" data-page="${x[0]}"><b>${x[1]}</b><span>${x[0]}</span></a>`).join('');nav.querySelectorAll('.nav-item').forEach(a=>a.onclick=()=>show(a.dataset.page))}
async function show(page){document.querySelectorAll('.nav-item').forEach(a=>a.classList.toggle('active',a.dataset.page===page));const c=$('#content');try{if(page==='Dashboard')return dashboard(c);if(page==='Inventory')return inventory(c);if(page==='Sales')return sales(c);if(page==='Purchases')return purchases(c);if(page==='Customers'||page==='Suppliers')return parties(c,page==='Customers'?'Customer':'Supplier');if(page==='Financing')return financing(c);if(page==='Payments')return payments(c);if(page==='Ledger')return ledger(c);if(page==='Users & Roles')return users(c);if(page==='Import / Export')return imports(c);if(page==='Reports')return reports(c);if(page==='Settings')return settings(c)}catch(e){notice(e.message,true)}}
function head(title,sub,buttons='',banner=false){const bannerHtml=banner?`<section class="growth-banner" aria-label="Sangam Nexus message"><div class="banner-cube" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i><i></i></div><button class="banner-arrow" type="button" aria-label="Previous message">‹</button><div class="banner-message"><p>“Together we grow, <span>Together we build</span>”</p><div class="banner-dots" aria-hidden="true"><i class="active"></i><i></i><i></i></div></div><button class="banner-arrow" type="button" aria-label="Next message">›</button></section>`:'';return bannerHtml+`<div class="page-head"><div><h1>${title}</h1><p class="subtitle">${sub}</p></div><div class="actions">${buttons}</div></div>`}
async function dashboard(c){const d=await api('/api/dashboard');c.innerHTML=head(`Good Morning, ${esc(user?.displayName||user?.username||'Admin')}! 👋`,'Here is what is happening with your business today.','<button class="btn primary" onclick="openOrder()">＋ Quick Action</button>',true)+`<div class="stats"><div class="stat"><span class="icon">💰</span><small>Total Revenue</small><strong>${money(d.totalRevenue)}</strong><small>↑ 18.6% from last month</small></div><div class="stat"><span class="icon">🛍️</span><small>Total Sales</small><strong>${d.totalSales}</strong><small>↑ 12.8% from last month</small></div><div class="stat"><span class="icon">🛒</span><small>Total Purchases</small><strong>${d.totalPurchases}</strong><small>↑ 9.3% from last month</small></div><div class="stat"><span class="icon">📦</span><small>Total Stock Value</small><strong>${money(d.totalStockValue)}</strong><small>Live stock position</small></div></div><div class="grid"><div class="card"><div class="card-head"><h3>Recent Orders</h3><button class="btn" onclick="show('Sales')">View All</button></div>${orderTable(d.orders,false)}</div><div class="card"><div class="card-head"><h3>Stock Alerts</h3></div><div class="dashboard-alert">⚠️ Low Stock <b>${d.lowStock}</b></div><div class="dashboard-alert">⛔ Out of Stock <b>${d.outOfStock}</b></div><div class="dashboard-alert">ℹ️ Expiring Soon <b>—</b></div></div></div><div class="grid" style="margin-top:16px"><div class="card"><div class="card-head"><h3>Top Products</h3></div>${productTable(d.products)}</div><div class="card"><div class="card-head"><h3>Quick Shortcuts</h3></div><div style="padding:16px;display:grid;gap:8px"><button class="btn primary" onclick="openOrder()">＋ New Sales Order</button><button class="btn" onclick="openPurchase()">＋ New Purchase</button><button class="btn" onclick="openProduct()">＋ Add Product</button><button class="btn" onclick="show('Payments')">💳 Record Payment</button></div></div></div>`}
function orderTable(rows,showActions=false){return `<div class="table-wrap"><table class="table"><thead><tr>${showActions?'<th>Action</th>':''}<th>Order</th><th>Type</th><th>Party</th><th>Product</th><th>Qty</th><th>Total</th><th>Status</th></tr></thead><tbody>${rows.map(o=>`<tr>${showActions?`<td><div class="actions"><button class="btn" onclick="printBill('${esc(o.bill_number||o.order_number)}')">🖨 Bill</button><button class="btn" onclick="editOrder(${o.id})">Edit</button><button class="btn danger" onclick="deleteOrder(${o.id})">Delete</button></div></td>`:''}<td>${esc(o.order_number)}</td><td><span class="pill ${o.order_type==='RX'?'amber':'blue'}">${o.order_type||'FSV'}</span></td><td>${esc(o.party_name||o.customer_name)}</td><td>${esc(o.brand)} — ${esc(o.product_name)}</td><td>${o.quantity}</td><td>${money(o.quantity*o.unit_price)}</td><td><span class="pill ${o.status==='Cancelled'?'red':o.status==='Shipped'?'blue':'green'}">${o.status}</span></td></tr>`).join('')||`<tr><td colspan="${showActions?8:7}"><div class="empty">No orders yet.</div></td></tr>`}</tbody></table></div>`}

// ---- Sales Bill / Invoice print view (navy & gold design) ----
async function printBill(billNumber){
  const key=String(billNumber||'').trim();
  if(!key)return notice('This order has no bill number to print.',true);
  let rows=(cache.orders||[]).filter(o=>o.status!=='Cancelled' && String(o.bill_number||o.order_number)===key);
  if(!rows.length){cache.orders=await api('/api/orders');rows=cache.orders.filter(o=>o.status!=='Cancelled' && String(o.bill_number||o.order_number)===key)}
  if(!rows.length)return notice('No line items found for bill '+key+'.',true);
  if(!cache.parties||!cache.parties.length)cache.parties=await api('/api/parties');
  const first=rows[0];
  const party=cache.parties.find(p=>p.id===first.party_id);
  const companyName=($('#company-select option:checked')||{}).textContent||'Sangam Nexus';
  const customerName=esc(first.party_name||first.customer_name||'');
  const address=esc(party&&party.address||'');
  const phone=esc(party&&party.phone||'');
  const billDate=esc(first.bill_date||first.order_date||today());
  const subtotal=rows.reduce((a,r)=>a+Number(r.quantity)*Number(r.unit_price),0);
  const vat=subtotal*0.13;
  const grandTotal=subtotal+vat;
  const itemsHtml=rows.map((r,i)=>`<tr><td class="c">${i+1}</td><td>${esc(r.brand)} — ${esc(r.product_name)}</td><td class="c">${r.quantity}</td><td class="r">${money(r.unit_price).replace('Rs. ','')}</td><td class="r">${money(r.quantity*r.unit_price).replace('Rs. ','')}</td></tr>`).join('');
  const html=`<!doctype html><html><head><meta charset="utf-8"><title>Sales Bill ${esc(key)}</title><style>
${BILL_CSS}
</style></head><body>
<div class="bill">
  <div class="gold-bar"></div>
  <div class="bill-header"><h1>${esc(companyName).toUpperCase()}</h1><p>Business Address, City, Nepal &nbsp;|&nbsp; PAN/VAT: XXXXXXXXX &nbsp;|&nbsp; Ph: XXXXXXXXXX</p></div>
  <div class="gold-bar"></div>
  <h2 class="bill-title">SALES BILL</h2>
  <div class="meta-grid">
    <div class="meta-box"><div class="meta-head">Bill To</div><div class="meta-body"><b>${customerName}</b><br>${address}${address&&phone?' &nbsp;|&nbsp; ':''}${phone}</div></div>
    <div class="meta-box"><div class="meta-head">Bill Details</div><div class="meta-body">Bill No.: <b>${esc(key)}</b><br>Date: <b>${billDate}</b></div></div>
  </div>
  <table class="items"><thead><tr><th>S.N.</th><th>Description of Goods / Items</th><th>Qty</th><th>Rate (Rs.)</th><th>Amount (Rs.)</th></tr></thead>
  <tbody>${itemsHtml}</tbody></table>
  <table class="totals">
    <tr><td>Sub Total</td><td class="r">${subtotal.toLocaleString(undefined,{maximumFractionDigits:2})}</td></tr>
    <tr><td>VAT @ 13%</td><td class="r">${vat.toLocaleString(undefined,{maximumFractionDigits:2})}</td></tr>
    <tr class="grand"><td>GRAND TOTAL (Rs.)</td><td class="r">${grandTotal.toLocaleString(undefined,{maximumFractionDigits:2})}</td></tr>
  </table>
  <p class="note">Note: Goods once sold will not be taken back or exchanged.</p>
  <p class="thanks">Thank you for your business!</p>
  <div class="sign-row"><div>Customer Signature</div><div>Authorized Signature</div></div>
  <div class="gold-bar"></div>
</div>
<script>window.onload=()=>{window.print()}</script>
</body></html>`;
  const w=window.open('','_blank','width=850,height=1000');
  if(!w)return notice('Please allow pop-ups to print the bill.',true);
  w.document.write(html);w.document.close();w.focus()
}
const BILL_CSS=`
:root{--navy:#16324F;--gold:#C9A227;--light:#EAF1FB;--grey:#6B7280}
*{box-sizing:border-box}
body{font-family:Calibri,Arial,sans-serif;color:#1a1a1a;margin:0;padding:24px;background:#fff}
.bill{max-width:760px;margin:0 auto;border:1px solid #d8dee6}
.gold-bar{height:6px;background:var(--gold)}
.bill-header{background:var(--navy);color:#fff;text-align:center;padding:18px 10px 12px}
.bill-header h1{margin:0;font-size:28px;letter-spacing:1px}
.bill-header p{margin:6px 0 0;font-size:11px;font-style:italic;opacity:.9}
.bill-title{text-align:center;color:var(--navy);font-size:20px;margin:18px 0 14px}
.meta-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px;padding:0 20px;margin-bottom:16px}
.meta-box{border:1px solid #d8dee6}
.meta-head{background:var(--navy);color:#fff;font-weight:bold;font-size:12px;padding:6px 10px}
.meta-body{background:var(--light);font-size:12px;padding:10px;line-height:1.6}
table.items{width:calc(100% - 40px);margin:0 20px;border-collapse:collapse}
table.items th{background:var(--navy);color:#fff;font-size:12px;padding:8px;text-align:left}
table.items td{border:1px solid #d8dee6;padding:7px 8px;font-size:12px}
table.items td.c{text-align:center}table.items td.r{text-align:right}
table.totals{width:calc(100% - 40px);margin:14px 20px 0;border-collapse:collapse}
table.totals td{padding:7px 10px;font-size:13px;background:var(--light);border:1px solid #d8dee6}
table.totals td:first-child{text-align:right;font-weight:600;color:var(--navy);width:80%}
table.totals td.r{text-align:right}
table.totals tr.grand td{background:var(--navy);color:#fff;font-weight:bold;font-size:14px}
.note{font-size:11px;font-style:italic;color:var(--grey);padding:0 20px;margin:16px 0 0}
.thanks{text-align:center;font-weight:bold;font-style:italic;color:var(--navy);margin:8px 0 26px}
.sign-row{display:flex;justify-content:space-between;padding:0 40px 24px;font-size:12px;font-weight:600;color:var(--navy)}
.sign-row div{border-top:1px solid #999;padding-top:6px;width:200px;text-align:center}
@media print{body{padding:0}.bill{border:none;max-width:100%}}
`;
function productTable(rows){return `<div class="table-wrap"><table class="table"><thead><tr><th>Product</th><th>Stock</th><th>Sold</th><th>Return</th><th>RX</th></tr></thead><tbody>${rows.map(p=>`<tr><td>${esc(p.brand)} — ${esc(p.name)}</td><td>${p.current_stock}</td><td>${p.sold}</td><td>${p.returned}</td><td>${p.is_rx?'Yes':'No'}</td></tr>`).join('')||`<tr><td colspan="5"><div class="empty">No products.</div></td></tr>`}</tbody></table></div>`}
async function inventory(c){cache.products=await api('/api/products');c.innerHTML=head('Inventory','Current stock = opening + purchases + returns − sales − FOC.','<button class="btn" onclick="openImport()">Import / Export</button><button class="btn primary" onclick="openProduct()">＋ Add Product</button><button class="btn danger" onclick="bulkDelete()">Delete Selected</button>')+`<div class="toolbar"><input id="inv-search" placeholder="Search brand or product..."><label><input type="checkbox" id="select-all"> Select All</label></div><div class="card">${productTableSelectable(cache.products)}</div>`;$('#select-all').onchange=e=>document.querySelectorAll('.product-check').forEach(x=>x.checked=e.target.checked);$('#inv-search').oninput=e=>document.querySelectorAll('#inv-body tr').forEach(r=>r.hidden=!r.textContent.toLowerCase().includes(e.target.value.toLowerCase()))}
function productTableSelectable(ps){return `<div class="table-wrap"><table class="table"><thead><tr><th></th><th>Brand</th><th>Product / SKU</th><th>Opening</th><th>Purchased</th><th>Sold</th><th>Return</th><th>FOC</th><th>Current</th><th>RX</th><th></th></tr></thead><tbody id="inv-body">${ps.map(p=>`<tr><td><input class="product-check" type="checkbox" value="${p.id}"></td><td>${esc(p.brand)}</td><td>${esc(p.name)}</td><td>${p.opening_stock}</td><td>${p.purchased}</td><td>${p.sold}</td><td>${p.returned}</td><td>${p.foc}</td><td><b>${p.current_stock}</b></td><td>${p.is_rx?'Yes':'No'}</td><td><button class="btn" onclick="editProduct(${p.id})">Edit</button></td></tr>`).join('')}</tbody></table></div>`}
async function sales(c){cache.orders=await api('/api/orders');c.innerHTML=head('Orders','Sales Order, Sales Return and FOC Issued use separate stock rules.','<button class="btn" onclick="openReturn()">↩ Sales Return</button><button class="btn" onclick="openFoc()">🎁 FOC Issued</button><button class="btn primary" onclick="openOrder()">＋ Sales Order</button>')+`<div class="card">${orderTable(cache.orders,true)}</div><div class="grid" style="margin-top:16px"><div class="card" id="returns-card"><div class="card-head"><h3>Sales Returns / Credit Notes</h3></div><div class="empty">Loading...</div></div><div class="card" id="foc-card"><div class="card-head"><h3>FOC Issued</h3></div><div class="empty">Loading...</div></div></div>`;const [r,f]=await Promise.all([api('/api/sales-returns'),api('/api/foc')]);$('#returns-card').innerHTML='<div class="card-head"><h3>Sales Returns / Credit Notes</h3></div>'+returnRows(r);$('#foc-card').innerHTML='<div class="card-head"><h3>FOC Issued</h3></div>'+focRows(f)}
function simpleRows(rows,keys){return `<div class="table-wrap"><table class="table"><thead><tr>${keys.map(k=>`<th>${k.replaceAll('_',' ')}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${keys.map(k=>`<td>${esc(r[k])}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${keys.length}"><div class="empty">No records.</div></td></tr>`}</tbody></table></div>`}
function returnRows(rows){return `<div class="table-wrap"><table class="table"><thead><tr><th>Return Number</th><th>Party</th><th>Product</th><th>Quantity</th><th>Credit Note</th><th>Action</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.return_number)}</td><td>${esc(r.party_name||'')}</td><td>${esc(r.product_name)}</td><td>${r.quantity}</td><td>${esc(r.credit_note_number)}</td><td><div class="actions"><button class="btn" onclick="editReturn(${r.id})">Edit</button><button class="btn danger" onclick="deleteReturn(${r.id})">Delete</button></div></td></tr>`).join('')||'<tr><td colspan="6"><div class="empty">No records.</div></td></tr>'}</tbody></table></div>`}
function focRows(rows){return `<div class="table-wrap"><table class="table"><thead><tr><th>FOC Number</th><th>Party</th><th>Product</th><th>Quantity</th><th>Action</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.foc_number)}</td><td>${esc(r.party_name||'')}</td><td>${esc(r.product_name)}</td><td>${r.quantity}</td><td><div class="actions"><button class="btn" onclick="editFoc(${r.id})">Edit</button><button class="btn danger" onclick="deleteFoc(${r.id})">Delete</button></div></td></tr>`).join('')||'<tr><td colspan="5"><div class="empty">No records.</div></td></tr>'}</tbody></table></div>`}
async function purchases(c){cache.purchases=await api('/api/purchases');c.innerHTML=head('Purchases','Every purchase increases stock.','<button class="btn" onclick="openImport()">Import / Export</button><button class="btn primary" onclick="openPurchase()">＋ New Purchase</button>')+`<div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Date</th><th>Product</th><th>Qty</th><th>Supplier</th><th>Reference</th><th>Action</th></tr></thead><tbody>${cache.purchases.map(p=>`<tr><td>${esc(p.purchase_date)}</td><td>${esc(p.brand)} — ${esc(p.product_name)}</td><td>${p.quantity}</td><td>${esc(p.supplier)}</td><td>${esc(p.reference)}</td><td><div class="actions"><button class="btn" onclick="editPurchase(${p.id})">Edit</button><button class="btn danger" onclick="deletePurchase(${p.id})">Delete</button></div></td></tr>`).join('')||'<tr><td colspan="6"><div class="empty">No purchases yet.</div></td></tr>'}</tbody></table></div></div>`}
async function parties(c,type){cache.parties=await api('/api/parties');const rows=cache.parties.filter(p=>type==='Customer'?p.type==='Customer'||p.type==='Both':p.type==='Supplier'||p.type==='Both');c.innerHTML=head(type+'s','Manage parties, opening balances and contact details.',`<button class="btn primary" onclick="openParty('${type}')">＋ Add ${type}</button>`)+`<div class="card">${simpleRows(rows,['name','type','phone','email','opening_balance'])}</div>`}
async function financing(c){const rows=await api('/api/financing');c.innerHTML=head('Financing','Sales bills and cumulative receivable position.','<button class="btn" onclick="show(\'Payments\')">Record Payment</button>')+`<div class="stats"><div class="stat"><small>Total Bills</small><strong>${rows.length}</strong></div><div class="stat"><small>Total Sales Bills</small><strong>${money(rows.reduce((a,r)=>a+r.total_amount,0))}</strong></div></div><div class="card">${financingRows(rows)}</div>`}
function financingRows(rows){return `<div class="table-wrap"><table class="table"><thead><tr><th>Party</th><th>Bill Number</th><th>Bill Date</th><th>Total Amount</th><th>Status</th><th>Action</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.party_name)}</td><td>${esc(r.bill_number)}</td><td>${esc(r.bill_date)}</td><td>${money(r.total_amount)}</td><td><span class="pill ${r.status==='Cancelled'?'red':r.status==='Shipped'?'blue':'green'}">${esc(r.status)}</span></td><td><button class="btn" onclick="printBill('${esc(r.bill_number)}')">🖨 Bill</button></td></tr>`).join('')||'<tr><td colspan="6"><div class="empty">No bills yet.</div></td></tr>'}</tbody></table></div>`}
async function payments(c){const rows=await api('/api/payments');c.innerHTML=head('Payments','Record money received from customers and paid to suppliers.','<button class="btn primary" onclick="openPayment()">＋ Record Payment</button>')+`<div class="card">${paymentRows(rows)}</div>`}
function paymentRows(rows){return `<div class="table-wrap"><table class="table"><thead><tr><th>Date</th><th>Party</th><th>Type</th><th>Amount</th><th>Bill Number</th><th>Reference</th><th>Action</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.payment_date)}</td><td>${esc(r.party_name||'Unassigned')}</td><td>${esc(r.payment_type)}</td><td>${money(r.amount)}</td><td>${esc(r.bill_number)}</td><td>${esc(r.reference)}</td><td><div class="actions"><button class="btn" onclick="editPayment(${r.id})">Edit</button><button class="btn danger" onclick="deletePayment(${r.id})">Delete</button></div></td></tr>`).join('')||'<tr><td colspan="7"><div class="empty">No payments yet.</div></td></tr>'}</tbody></table></div>`}
async function ledger(c){const parties=await api('/api/parties');c.innerHTML=head('Ledger','Select a party to see invoice, return and payment movements.','<button class="btn" onclick="window.print()">Print</button>')+`<div class="toolbar"><select id="ledger-party"><option value="">Select Party</option>${parties.map(p=>`<option value="${p.id}">${esc(p.name)} — ${esc(p.type)}</option>`).join('')}</select><input id="ledger-from" type="date" value="${today().slice(0,8)}01"><input id="ledger-to" type="date" value="${today()}"><button class="btn primary" onclick="loadLedger()">View Ledger</button></div><div id="ledger-result" class="card"><div class="empty">Select a party and click View Ledger.</div></div>`}
async function loadLedger(){const pid=Number($('#ledger-party').value);if(!pid)return notice('Select a party first.',true);const q=new URLSearchParams({from:$('#ledger-from').value,to:$('#ledger-to').value});const d=await api('/api/ledger/'+pid+'?'+q.toString());$('#ledger-result').innerHTML=`<div class="card-head"><h3>${esc(d.party.name)}</h3><b>Balance: ${money(d.balance)}</b></div><div class="table-wrap"><table class="table"><thead><tr><th>Date</th><th>Type</th><th>Reference</th><th>Qty</th><th>Debit</th><th>Credit</th><th>Balance</th></tr></thead><tbody>${d.rows.map(r=>`<tr><td>${esc(r.date)}</td><td>${esc(r.type)}</td><td>${esc(r.ref)}</td><td>${r.qty||''}</td><td>${money(r.debit)}</td><td>${money(r.credit)}</td><td>${money(r.balance)}</td></tr>`).join('')||'<tr><td colspan="7"><div class="empty">No ledger transactions.</div></td></tr>'}</tbody></table></div>`}
async function users(c){const rows=await api('/api/users');c.innerHTML=head('Users & Roles','Create users and decide exactly which modules they can open.','<button class="btn primary" onclick="openUser()">＋ Add User</button>')+`<div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>username</th><th>display name</th><th>role</th><th>active</th><th>actions</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.username)}</td><td>${esc(r.display_name)}</td><td>${esc(r.role)}</td><td>${esc(r.active)}</td><td><button class="btn" onclick="openEditUser(${r.id})">✎ Edit</button> <button class="btn danger" onclick="deleteUser(${r.id},'${esc(r.username)}')">🗑 Delete</button></td></tr>`).join('')||`<tr><td colspan="5"><div class="empty">No records.</div></td></tr>`}</tbody></table></div></div>`}
function deleteUser(id,username){if(user&&user.username===username)return notice('You cannot delete your own account while logged in as it.',true);confirmDelete(`Delete user "${username}"? This cannot be undone.`,async()=>{await api('/api/users/'+id,{method:'DELETE'});notice('User deleted.');show('Users & Roles')})}
async function imports(c){c.innerHTML=head('Import / Export','Click an action and select exactly what you want to import or export.','<button class="btn primary" onclick="openImport()">＋ Import / Export</button>')+`<div class="grid"><div class="card"><div class="card-head"><h3>Export</h3></div><div style="padding:16px;display:grid;gap:8px">${['inventory','orders','purchases','parties','payments','returns'].map(k=>`<button class="btn" onclick="downloadExport('${k}')">Export ${k}</button>`).join('')}</div></div><div class="card"><div class="card-head"><h3>Import</h3></div><div style="padding:16px"><p class="subtitle">Inventory and parties accept .xlsx files. Other templates can be added as the workflow expands.</p><button class="btn primary" onclick="importFile('inventory')">Import Inventory Excel</button><button class="btn" style="margin-top:8px" onclick="importFile('parties')">Import Parties Excel</button></div></div></div>`}
async function reports(c){const parties=await api('/api/parties');c.innerHTML=head('Reports','Choose a report, party and date range. Reports use live transaction data.','<button class="btn" onclick="downloadExport(\'inventory\')">Export Inventory</button>')+`<div class="card" style="padding:16px;margin-bottom:16px"><div class="form-row"><label>Report<select id="report-type"><option value="inventory">Inventory / Stock</option><option value="sales">Sales / Invoices</option><option value="purchases">Purchases</option><option value="payments">Payments</option><option value="returns">Sales Returns / Credit Notes</option><option value="foc">FOC Issued</option><option value="ledger">Party-wise Ledger</option></select></label><label>Party<select id="report-party"><option value="">All / Select Party</option>${parties.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></label></div><div class="form-row"><label>From<input id="report-from" type="date" value="${today().slice(0,8)}01"></label><label>To<input id="report-to" type="date" value="${today()}"></label></div><div class="form-actions"><button class="btn primary" onclick="runReport()">Run Report</button></div></div><div id="report-result" class="card"><div class="empty">Choose a report and click Run Report.</div></div>`}
async function runReport(){const type=$('#report-type').value,pid=$('#report-party').value;if(type==='ledger'&&!pid)return notice('Select a party for Ledger report.',true);const q=new URLSearchParams({type,from:$('#report-from').value,to:$('#report-to').value});if(pid)q.set('partyId',pid);const rows=await api('/api/reports?'+q.toString());let keys=[];if(type==='inventory')keys=['brand','name','opening_stock','purchased','sold','returned','foc','current_stock','is_rx'];else if(type==='sales')keys=['order_date','order_number','order_type','party_name','product_name','quantity','unit_price','bill_number','status'];else if(type==='purchases')keys=['purchase_date','brand','product_name','quantity','supplier','reference'];else if(type==='payments')keys=['payment_date','party_name','payment_type','amount','bill_number','reference'];else if(type==='returns')keys=['return_date','return_number','party_name','product_name','quantity','unit_price','credit_note_number'];else if(type==='foc')keys=['issue_date','foc_number','party_name','product_name','quantity'];else keys=['date','type','reference','quantity','amount'];$('#report-result').innerHTML=Array.isArray(rows)?simpleRows(rows,keys):'<div class="empty">No report data.</div>'}
async function settings(c){const cs=await fetch('/api/companies').then(r=>r.json());c.innerHTML=head('Settings','Company management and developer information.','<button class="btn primary" onclick="openCompany()">＋ Add Company</button>')+`<div class="grid"><div class="card"><div class="card-head"><h3>Companies</h3></div>${simpleRows(cs,['name','code','active'])}</div><div class="card"><div class="card-head"><h3>Developer</h3></div><div style="padding:18px;line-height:2;font-size:13px"><b>Sangam Bhusal</b><br>sangam23bhusal@gmail.com<br>+977 9761691545<br><small>Developer & System Administrator</small></div></div></div>`}
function formHtml(fields){return `<div class="form">${fields.join('')}<div class="form-actions"><button type="button" class="btn" onclick="$('#modal').hidden=true">Cancel</button><button class="btn primary">Save</button></div></div>`}const input=(label,name,val='',type='text',extra='')=>`<label>${label}<input name="${name}" type="${type}" value="${esc(val)}" ${extra}></label>`;const select=(label,name,opts,val='')=>`<label>${label}<select name="${name}">${opts.map(o=>`<option value="${esc(o[0])}" ${String(o[0])===String(val)?'selected':''}>${esc(o[1])}</option>`).join('')}</select></label>`;
function modal(title,html,save){$('#modal-title').textContent=title;$('#form').innerHTML=html;$('#modal').hidden=false;$('#form').onsubmit=async e=>{e.preventDefault();try{await save(new FormData(e.target));$('#modal').hidden=true;show(currentPage())}catch(x){notice(x.message,true)}}}function currentPage(){return document.querySelector('.nav-item.active')?.dataset.page||'Dashboard'}
function productOptions(val=''){return cache.products.map(p=>[p.id,`${p.brand} — ${p.name}${p.is_rx?' [RX]':''} (stock ${p.current_stock})`])}
async function openProduct(){cache.products=await api('/api/products');modal('New Product',formHtml([input('Brand *','brand'),input('Product / SKU *','name'),input('Opening Stock','openingStock',0,'number','step="any" min="0"'),`<label><input type="checkbox" name="isRx"> RX / Direct Order Product</label>`]),async d=>api('/api/products',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(d))}))}
async function editProduct(id){const p=cache.products.find(x=>x.id===id)||await api('/api/products').then(a=>a.find(x=>x.id===id));modal('Edit Product',formHtml([input('Brand *','brand',p.brand),input('Product / SKU *','name',p.name),input('Opening Stock','openingStock',p.opening_stock,'number','step="any" min="0"'),`<label><input type="checkbox" name="isRx" ${p.is_rx?'checked':''}> RX / Direct Order Product</label>`]),async d=>api('/api/products/'+id,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(d))}))}
async function openOrder(){cache.products=await api('/api/products');cache.parties=await api('/api/parties');const fields=[select('Order Type *','orderType',[['FSV','FSV — From Stock'],['RX','RX — Direct / Special Order']]),input('Order Number','orderNumber','SO-'+Date.now()),input('Shop Name *','shopName'),input('Customer Name *','customerName'),select('Party','partyId',[['','Select party'],...cache.parties.map(p=>[p.id,p.name])]),`<div id="fsv-fields"><label>Product *<select name="productId"><option value="">Select FSV product</option>${cache.products.filter(p=>!p.is_rx).map(p=>`<option value="${p.id}">${esc(p.brand)} — ${esc(p.name)} (stock ${p.current_stock})</option>`).join('')}</select></label></div>`,`<div id="rx-fields" hidden>${input('RX Brand *','rxBrand')} ${input('RX Product / SKU *','rxProduct')} ${select('Source Country','rxSource',[['','Select source'],['India','India'],['Thailand','Thailand'],['Other','Other']])}</div>`,input('Quantity *','quantity','','number','required min="0.01" step="any"'),input('Unit Price','unitPrice',0,'number','min="0" step="any"'),select('Status','status',[['Pending','Pending'],['Processed','Processed'],['Shipped','Shipped'],['Cancelled','Cancelled']]),input('Order Date','orderDate',today(),'date'),input('Sales Bill Number','billNumber',''),input('Sales Bill Date','billDate',today(),'date'),input('Notes','notes')];modal('New Sales Order',formHtml(fields),async d=>api('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(d))}));const type=$('select[name=orderType]'),fsv=$('#fsv-fields'),rx=$('#rx-fields');const sync=()=>{const isRx=type.value==='RX';fsv.hidden=isRx;rx.hidden=!isRx;const p=$('select[name=productId]');if(p)p.required=!isRx;const b=$('input[name=rxBrand]'),n=$('input[name=rxProduct]');if(b)b.required=isRx;if(n)n.required=isRx};type.onchange=sync;sync()}
async function openPurchase(){cache.products=await api('/api/products');modal('New Purchase',formHtml([select('Product *','productId',[['','Select product'],...productOptions()]),input('Quantity *','quantity','','number','required min="0.01" step="any"'),input('Supplier','supplier'),input('Reference','reference'),input('Purchase Date','purchaseDate',today(),'date'),input('Notes','notes')]),async d=>api('/api/purchases',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(d))}))}
async function openReturn(){cache.products=await api('/api/products');cache.parties=await api('/api/parties');modal('Sales Return / Credit Note',formHtml([input('Return Number','returnNumber','SR-'+Date.now()),input('Bill Number','billNumber'),select('Party','partyId',[['','Select party'],...cache.parties.map(p=>[p.id,p.name])]),select('Product *','productId',[['','Select product'],...productOptions()]),input('Quantity *','quantity','','number','required min="0.01" step="any"'),input('Unit Price','unitPrice',0,'number'),input('Return Date','returnDate',today(),'date'),input('Credit Note Number','creditNoteNumber','CN-'+Date.now()),input('Notes','notes')]),async d=>api('/api/sales-returns',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(d))}))}
async function openFoc(){cache.products=await api('/api/products');cache.parties=await api('/api/parties');modal('FOC Issued',formHtml([input('FOC Number','focNumber','FOC-'+Date.now()),select('Party','partyId',[['','Select party'],...cache.parties.map(p=>[p.id,p.name])]),select('Product *','productId',[['','Select product'],...productOptions()]),input('Quantity *','quantity','','number','required min="0.01" step="any"'),input('Issue Date','issueDate',today(),'date'),input('Notes','notes')]),async d=>api('/api/foc',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(d))}))}
async function openParty(type){modal('Add '+type,formHtml([input('Party Name *','name'),select('Type','type',[[type,type],['Both','Both']]),input('Phone','phone'),input('Email','email',''),input('Address','address'),input('Opening Balance','openingBalance',0,'number')]),async d=>api('/api/parties',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(d))}))}
async function openPayment(){cache.parties=await api('/api/parties');modal('Record Payment',formHtml([select('Party','partyId',[['','Select party'],...cache.parties.map(p=>[p.id,p.name])]),select('Payment Type','paymentType',[['Received','Received'],['Paid','Paid']]),input('Amount *','amount','','number','required min="0.01" step="any"'),input('Payment Date','paymentDate',today(),'date'),input('Bill Number','billNumber'),input('Reference','reference'),input('Notes','notes')]),async d=>api('/api/payments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(d))}))}
async function openUser(){const ms=modules.map(x=>x[0]);modal('Add User',formHtml([input('Username *','username'),input('Password *','password','','password','required'),input('Display Name *','displayName'),select('Role','role',[['User','User'],['Admin','Admin']]),`<div><b>Module Access</b><div class="check-list">${ms.map(m=>`<label><input type="checkbox" name="perm_${esc(m)}" checked> ${esc(m)}</label>`).join('')}</div></div>`]),async d=>{const obj=Object.fromEntries(d),perms={};ms.forEach(m=>perms[m]=d.get('perm_'+m)==='on');obj.permissions=perms;return api('/api/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(obj)})})}
async function openEditUser(id){const list=await api('/api/users');const u=list.find(x=>x.id===id);if(!u)return notice('User not found.',true);const perms=await api('/api/users/'+id+'/permissions');const permMap={};perms.forEach(p=>permMap[p.module]=!!p.allowed);const ms=modules.map(x=>x[0]);modal('Edit User — '+u.username,formHtml([input('New Password (leave blank to keep current)','password','','password'),input('Display Name *','displayName',u.display_name),select('Role','role',[['User','User'],['Admin','Admin']],u.role),`<div><b>Module Access</b><div class="check-list">${ms.map(m=>`<label><input type="checkbox" name="perm_${esc(m)}" ${permMap[m]!==false?'checked':''}> ${esc(m)}</label>`).join('')}</div></div>`]),async d=>{const obj=Object.fromEntries(d),perms={};ms.forEach(m=>perms[m]=d.get('perm_'+m)==='on');obj.permissions=perms;if(!obj.password)delete obj.password;return api('/api/users/'+id,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(obj)})})}
function openCompany(){modal('Add Company',formHtml([input('Company Name *','name'),input('Company Code *','code')]),async d=>{const obj=Object.fromEntries(d);obj.createdByUsername=user?.username||'';const r=await fetch('/api/companies',{method:'POST',headers:{'Content-Type':'application/json','x-company-id':companyId},body:JSON.stringify(obj)});const x=await r.json();if(!r.ok)throw Error(x.error);companyId=x.id;$('#company-select').innerHTML+=(new Option(x.name,x.id)).outerHTML;$('#company-select').value=x.id;const lr=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json','x-company-id':companyId},body:JSON.stringify({companyId,username:user.username,password:$('#login-pass').value})});if(lr.ok){const ld=await lr.json();user=ld.user;permissions=ld.permissions;localStorage.setItem('nexusSession',JSON.stringify({companyId,user,permissions}));renderNav();await show('Dashboard')}})}
function openImport(){show('Import / Export')}
async function importFile(kind){const i=document.createElement('input');i.type='file';i.accept='.xlsx,.xls';i.onchange=async()=>{if(!i.files[0])return;const fd=new FormData();fd.append('file',i.files[0]);try{const r=await fetch('/api/import/'+kind,{method:'POST',headers:{'x-company-id':companyId},body:fd});const d=await r.json();if(!r.ok)throw Error(d.error);notice(`${d.imported} row(s) imported.`);show(currentPage())}catch(e){notice(e.message,true)}};i.click()}
function downloadExport(kind){window.location.href='/api/export-xlsx/'+kind+'?companyId='+companyId}
async function editOrder(id){cache.products=await api('/api/products');cache.parties=await api('/api/parties');const o=cache.orders.find(x=>x.id===id)||await api('/api/orders').then(a=>a.find(x=>x.id===id));const type=o.order_type||'FSV';const fields=[select('Order Type *','orderType',[[type,type],...(type==='RX'?[['FSV','FSV — From Stock']]:[['RX','RX — Direct / Special Order']])],type),input('Order Number','orderNumber',o.order_number),input('Shop Name *','shopName',o.shop_name),input('Customer Name *','customerName',o.customer_name),select('Party','partyId',[['','Select party'],...cache.parties.map(p=>[p.id,p.name])],o.party_id||''),type==='RX'?input('RX Brand *','rxBrand',o.brand):select('Product *','productId',[['','Select product'],...cache.products.filter(p=>!p.is_rx).map(p=>[p.id,`${p.brand} — ${p.name} (stock ${p.current_stock})`])],o.product_id),type==='RX'?input('RX Product / SKU *','rxProduct',o.product_name):input('RX Product / SKU','rxProduct',''),type==='RX'?input('Source Country','rxSource',(o.notes||'').split(' | ')[0]||''):input('Notes','notes',o.notes||''),input('Quantity *','quantity',o.quantity,'number','required min="0.01" step="any"'),input('Unit Price','unitPrice',o.unit_price,'number','min="0" step="any"'),select('Status','status',[['Pending','Pending'],['Processed','Processed'],['Shipped','Shipped'],['Cancelled','Cancelled']],o.status),input('Order Date','orderDate',o.order_date,'date'),input('Sales Bill Number','billNumber',o.bill_number||o.order_number),input('Sales Bill Date','billDate',o.bill_date||o.order_date,'date')];modal('Edit Sales Order',formHtml(fields),async d=>api('/api/orders/'+id,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(d))}))}
async function editPurchase(id){cache.products=await api('/api/products');const p=cache.purchases.find(x=>x.id===id)||await api('/api/purchases').then(a=>a.find(x=>x.id===id));modal('Edit Purchase',formHtml([select('Product *','productId',[['','Select product'],...productOptions()],p.product_id),input('Quantity *','quantity',p.quantity,'number','required min="0.01" step="any"'),input('Supplier','supplier',p.supplier),input('Reference','reference',p.reference),input('Purchase Date','purchaseDate',p.purchase_date,'date'),input('Notes','notes',p.notes||'')]),async d=>api('/api/purchases/'+id,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(d))}))}
async function editReturn(id){cache.products=await api('/api/products');cache.parties=await api('/api/parties');const r=await api('/api/sales-returns').then(a=>a.find(x=>x.id===id));modal('Edit Sales Return / Credit Note',formHtml([input('Return Number','returnNumber',r.return_number),input('Bill Number','billNumber',r.bill_number||''),select('Party','partyId',[['','Select party'],...cache.parties.map(p=>[p.id,p.name])],r.party_id||''),select('Product *','productId',[['','Select product'],...productOptions()],r.product_id),input('Quantity *','quantity',r.quantity,'number','required min="0.01" step="any"'),input('Unit Price','unitPrice',r.unit_price,'number'),input('Return Date','returnDate',r.return_date,'date'),input('Credit Note Number','creditNoteNumber',r.credit_note_number),input('Notes','notes',r.notes||'')]),async d=>api('/api/sales-returns/'+id,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(d))}))}
async function editFoc(id){cache.products=await api('/api/products');cache.parties=await api('/api/parties');const f=await api('/api/foc').then(a=>a.find(x=>x.id===id));modal('Edit FOC',formHtml([input('FOC Number','focNumber',f.foc_number),select('Party','partyId',[['','Select party'],...cache.parties.map(p=>[p.id,p.name])],f.party_id||''),select('Product *','productId',[['','Select product'],...productOptions()],f.product_id),input('Quantity *','quantity',f.quantity,'number','required min="0.01" step="any"'),input('Issue Date','issueDate',f.issue_date,'date'),input('Notes','notes',f.notes||'')]),async d=>api('/api/foc/'+id,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(d))}))}
async function editPayment(id){cache.parties=await api('/api/parties');const r=await api('/api/payments').then(a=>a.find(x=>x.id===id));modal('Edit Payment',formHtml([select('Party','partyId',[['','Select party'],...cache.parties.map(p=>[p.id,p.name])],r.party_id||''),select('Payment Type','paymentType',[['Received','Received'],['Paid','Paid']],r.payment_type),input('Amount *','amount',r.amount,'number','required min="0.01" step="any"'),input('Payment Date','paymentDate',r.payment_date,'date'),input('Bill Number','billNumber',r.bill_number||''),input('Reference','reference',r.reference||''),input('Notes','notes',r.notes||'')]),async d=>api('/api/payments/'+id,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(d))}))}
function confirmDelete(message,onConfirm){$('#modal-title').textContent='Delete record?';$('#form').innerHTML=`<p class="subtitle" style="margin:0 0 18px">${esc(message)}</p><div class="form-actions"><button type="button" class="btn" id="delete-cancel">Cancel</button><button type="button" class="btn danger" id="delete-confirm">Delete</button></div>`;$('#modal').hidden=false;$('#delete-cancel').onclick=()=>$('#modal').hidden=true;$('#delete-confirm').onclick=async()=>{try{$('#delete-confirm').disabled=true;await onConfirm();$('#modal').hidden=true}catch(e){notice(e.message,true);$('#modal').hidden=true}}}
function deletePurchase(id){confirmDelete('Delete this purchase? Stock will be recalculated.',async()=>{await api('/api/purchases/'+id,{method:'DELETE'});notice('Purchase deleted. Stock updated.');show('Purchases')})}
function deleteOrder(id){confirmDelete('Delete this sales order? Any linked payment will also be removed so Ledger stays synchronized.',async()=>{await api('/api/orders/'+id,{method:'DELETE'});notice('Sales order deleted. Linked Ledger/payment data and stock totals updated.');show('Sales')})}
function deleteReturn(id){confirmDelete('Delete this sales return? Its linked Credit Note will also be deleted.',async()=>{await api('/api/sales-returns/'+id,{method:'DELETE'});notice('Sales return and linked Credit Note deleted. Ledger and stock updated.');show('Sales')})}
function deleteFoc(id){confirmDelete('Delete this FOC record? Stock will be restored automatically.',async()=>{await api('/api/foc/'+id,{method:'DELETE'});notice('FOC deleted. Stock updated.');show('Sales')})}
function deletePayment(id){confirmDelete('Delete this payment? Ledger will be recalculated immediately.',async()=>{await api('/api/payments/'+id,{method:'DELETE'});notice('Payment deleted. Ledger updated.');show('Payments')})}
async function bulkDelete(){const ids=[...document.querySelectorAll('.product-check:checked')].map(x=>Number(x.value));if(!ids.length)return notice('Select at least one product.',true);if(!confirm(`Delete ${ids.length} selected product(s)? Products with opening stock or any history will be blocked.`))return;try{await api('/api/products/bulk-delete',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids})});notice('Selected products deleted.');show('Inventory')}catch(e){notice(e.message,true);show('Inventory')}}
function notice(m,error=false){const n=$('#notice');n.textContent=m;n.className='notice'+(error?' error':'');n.hidden=false;setTimeout(()=>n.hidden=true,5000)}
$('#company-select').onchange=async e=>{companyId=Number(e.target.value);const r=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json','x-company-id':companyId},body:JSON.stringify({companyId,username:user.username,password:$('#login-pass').value})});if(r.ok){const d=await r.json();permissions=d.permissions;localStorage.setItem('nexusSession',JSON.stringify({companyId,user,permissions}));renderNav();show('Dashboard')}else notice('Your user is not assigned to this company.',true)};
boot();

