const express=require('express');
const multer=require('multer');
const XLSX=require('xlsx');
const path=require('path');
const {db,shivaayId,product,products,assertStock,orderWithProduct,purchaseWithProduct}=require('./db');
const app=express(),upload=multer({storage:multer.memoryStorage(),limits:{fileSize:10*1024*1024}});
app.use(express.json());app.use(express.static(__dirname));
const today=()=>new Date().toISOString().slice(0,10);
const n=(v,label,positive=false)=>{const x=Number(v);if(!Number.isFinite(x)||(positive&&x<=0))throw Error(`${label} must be ${positive?'greater than zero':'a number'}.`);return x};
const must=(v,label)=>{if(!String(v??'').trim())throw Error(`${label} is required.`);return String(v).trim()};
const tx=fn=>db.transaction(fn)();
const http=fn=>(req,res)=>{try{res.json(fn(req,res))}catch(e){res.status(/insufficient stock/i.test(e.message)?409:400).json({error:e.message})}};
const companyId=req=>Number(req.headers['x-company-id']||req.query.companyId||shivaayId);
const listOrders=c=>db.prepare(`SELECT o.*,p.brand,p.name product_name,p.is_rx,pa.name party_name FROM orders o JOIN products p ON p.id=o.product_id LEFT JOIN parties pa ON pa.id=o.party_id WHERE o.company_id=? ORDER BY o.order_date DESC,o.id DESC`).all(c);
const listPurchases=c=>db.prepare(`SELECT pu.*,p.brand,p.name product_name FROM purchases pu JOIN products p ON p.id=pu.product_id WHERE pu.company_id=? ORDER BY pu.purchase_date DESC,pu.id DESC`).all(c);
function validProduct(data,c){const p=product(Number(data.productId),c);if(!p)throw Error('Choose a valid product.');return p}
function ensureParty(c,partyId,name,type='Customer'){if(partyId){const p=db.prepare('SELECT id FROM parties WHERE id=? AND company_id=?').get(Number(partyId),c);if(!p)throw Error('Select a valid party.');return Number(p.id)}const clean=String(name||'').trim();if(!clean)return null;const existing=db.prepare('SELECT id FROM parties WHERE company_id=? AND name=?').get(c,clean);if(existing)return Number(existing.id);const r=db.prepare('INSERT INTO parties(company_id,name,type) VALUES(?,?,?)').run(c,clean,type);return Number(r.lastInsertRowid)}
app.get('/api/companies',http(()=>db.prepare('SELECT * FROM companies WHERE active=1 ORDER BY id').all()));
app.post('/api/companies',http(req=>tx(()=>{const name=must(req.body.name,'Company name'),code=must(req.body.code,'Company code').toUpperCase();const r=db.prepare('INSERT INTO companies(name,code) VALUES(?,?)').run(name,code);const newCompanyId=Number(r.lastInsertRowid);const username=String(req.body.createdByUsername||'').trim();if(username){const current=db.prepare('SELECT * FROM users WHERE company_id=? AND username=? AND active=1').get(companyId(req),username);if(current){const u=db.prepare('INSERT INTO users(company_id,username,password,display_name,role) VALUES(?,?,?,?,?)').run(newCompanyId,current.username,current.password,current.display_name,current.role);const perms=db.prepare('SELECT module,allowed FROM user_permissions WHERE user_id=?').all(current.id);const ins=db.prepare('INSERT INTO user_permissions(user_id,module,allowed) VALUES(?,?,?)');perms.forEach(x=>ins.run(u.lastInsertRowid,x.module,x.allowed));}}return db.prepare('SELECT * FROM companies WHERE id=?').get(newCompanyId)})));
app.get('/api/dashboard',http(req=>{const c=companyId(req);const ord=listOrders(c),pur=listPurchases(c),ps=products(c);const sales=ord.filter(o=>o.status!=='Cancelled').reduce((a,o)=>a+o.quantity*o.unit_price,0);const purchases=pur.reduce((a,o)=>a+o.quantity*Number(o.unit_price||0),0);return {totalRevenue:sales,totalSales:ord.filter(o=>o.status!=='Cancelled').length,totalPurchases:pur.length,totalStockValue:ps.reduce((a,p)=>a+Math.max(0,p.current_stock)*Number(p.unit_price||0),0),orders:ord.slice(0,5),products:ps.slice(0,8),lowStock:ps.filter(p=>p.current_stock<=5).length,outOfStock:ps.filter(p=>p.current_stock<=0).length,purchasesValue:purchases}}));
app.get('/api/products',http(req=>products(companyId(req))));
app.post('/api/products',http(req=>tx(()=>{const c=companyId(req),b=must(req.body.brand,'Brand'),name=must(req.body.name,'Product'),opening=n(req.body.openingStock||0,'Opening stock');const r=db.prepare('INSERT INTO products(company_id,brand,name,opening_stock,is_rx) VALUES(?,?,?,?,?)').run(c,b,name,opening,req.body.isRx?1:0);return product(r.lastInsertRowid,c)})));
app.put('/api/products/:id',http(req=>tx(()=>{const c=companyId(req),id=Number(req.params.id),p=product(id,c);if(!p)throw Error('Product not found.');const opening=n(req.body.openingStock,'Opening stock');assertStock(id,c,opening-p.opening_stock);db.prepare('UPDATE products SET brand=?,name=?,opening_stock=?,is_rx=? WHERE id=? AND company_id=?').run(must(req.body.brand,'Brand'),must(req.body.name,'Product'),opening,req.body.isRx?1:0,id,c);return product(id,c)})));
app.delete('/api/products/:id',http(req=>tx(()=>{const c=companyId(req),id=Number(req.params.id),p=product(id,c);if(!p)throw Error('Product not found.');if(p.opening_stock!==0||db.prepare(`SELECT 1 FROM purchases WHERE product_id=? UNION SELECT 1 FROM orders WHERE product_id=? UNION SELECT 1 FROM sales_returns WHERE product_id=? UNION SELECT 1 FROM foc_issues WHERE product_id=?`).get(id,id,id,id))throw Error('This product has opening stock or transaction history and cannot be deleted.');db.prepare('DELETE FROM products WHERE id=? AND company_id=?').run(id,c);return{ok:true}})));
app.post('/api/products/bulk-delete',http(req=>tx(()=>{const c=companyId(req),ids=(req.body.ids||[]).map(Number);if(!ids.length)throw Error('Select at least one product.');let deleted=0,blocked=[];for(const id of ids){const p=product(id,c);if(!p)continue;const used=db.prepare(`SELECT 1 FROM purchases WHERE product_id=? UNION SELECT 1 FROM orders WHERE product_id=? UNION SELECT 1 FROM sales_returns WHERE product_id=? UNION SELECT 1 FROM foc_issues WHERE product_id=?`).get(id,id,id,id);if(p.opening_stock!==0||used){blocked.push(`${p.brand} — ${p.name}`);continue}db.prepare('DELETE FROM products WHERE id=? AND company_id=?').run(id,c);deleted++}if(blocked.length)throw Error(`${deleted} deleted. Blocked: ${blocked.slice(0,5).join(', ')}${blocked.length>5?' and more.':''}`);return{deleted}})));
app.get('/api/purchases',http(req=>listPurchases(companyId(req))));
app.post('/api/purchases',http(req=>tx(()=>{const c=companyId(req),p=validProduct(req.body,c),q=n(req.body.quantity,'Quantity',true);const r=db.prepare('INSERT INTO purchases(company_id,product_id,quantity,supplier,reference,purchase_date,notes) VALUES(?,?,?,?,?,?,?)').run(c,p.id,q,req.body.supplier||'',req.body.reference||'',req.body.purchaseDate||today(),req.body.notes||'');return purchaseWithProduct(r.lastInsertRowid,c)})));
app.put('/api/purchases/:id',http(req=>tx(()=>{const c=companyId(req),id=Number(req.params.id),old=purchaseWithProduct(id,c);if(!old)throw Error('Purchase not found.');const p=validProduct(req.body,c),q=n(req.body.quantity,'Quantity',true);if(old.product_id===p.id){/* derived stock needs no manual adjustment */}db.prepare('UPDATE purchases SET product_id=?,quantity=?,supplier=?,reference=?,purchase_date=?,notes=? WHERE id=? AND company_id=?').run(p.id,q,req.body.supplier||'',req.body.reference||'',req.body.purchaseDate||today(),req.body.notes||'',id,c);return purchaseWithProduct(id,c)})));
app.delete('/api/purchases/:id',http(req=>tx(()=>{const c=companyId(req),p=purchaseWithProduct(Number(req.params.id),c);if(!p)throw Error('Purchase not found.');db.prepare('DELETE FROM purchases WHERE id=? AND company_id=?').run(p.id,c);return{ok:true}})));
app.get('/api/orders',http(req=>listOrders(companyId(req))));
app.post('/api/orders',http(req=>tx(()=>{const c=companyId(req),type=String(req.body.orderType||'FSV').toUpperCase(),q=n(req.body.quantity,'Quantity',true),status=req.body.status||'Pending';if(!['FSV','RX'].includes(type))throw Error('Order type must be FSV or RX.');let p;if(type==='RX'){const brand=must(req.body.rxBrand,'RX brand'),name=must(req.body.rxProduct,'RX product');p=db.prepare('SELECT * FROM products WHERE company_id=? AND brand=? AND name=? AND is_rx=1 AND active=1').get(c,brand,name);if(!p){const rprod=db.prepare('INSERT INTO products(company_id,brand,name,opening_stock,is_rx,active) VALUES(?,?,?,?,?,1)').run(c,brand,name,0,1);p=product(Number(rprod.lastInsertRowid),c);} }else{p=validProduct(req.body,c);if(p.is_rx)throw Error('RX product cannot be used as FSV. Choose FSV or create a new RX order.');if(status!=='Cancelled')assertStock(p.id,c,-q);}const partyId=ensureParty(c,req.body.partyId,req.body.customerName,'Customer');const number=String(req.body.orderNumber||`SO-${Date.now()}`);const source=type==='RX' ? [req.body.rxSource||'',req.body.notes||''].filter(Boolean).join(' | ') : (req.body.notes||'');const r=db.prepare(`INSERT INTO orders(company_id,order_number,shop_name,customer_name,party_id,product_id,quantity,unit_price,status,order_date,bill_number,bill_date,notes,order_type) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(c,number,must(req.body.shopName,'Shop name'),must(req.body.customerName,'Customer name'),partyId,p.id,q,n(req.body.unitPrice||0,'Unit price'),status,req.body.orderDate||today(),req.body.billNumber||number,req.body.billDate||req.body.orderDate||today(),source,type);return orderWithProduct(r.lastInsertRowid,c)})));
app.put('/api/orders/:id',http(req=>tx(()=>{const c=companyId(req),old=orderWithProduct(Number(req.params.id),c);if(!old)throw Error('Order not found.');const type=String(req.body.orderType||old.order_type||'FSV').toUpperCase(),q=n(req.body.quantity,'Quantity',true),status=req.body.status||'Pending';if(!['FSV','RX'].includes(type))throw Error('Order type must be FSV or RX.');let p;if(type==='RX'){const brand=must(req.body.rxBrand||req.body.brand||old.brand,'RX brand'),name=must(req.body.rxProduct||req.body.productName||old.product_name,'RX product');p=db.prepare('SELECT * FROM products WHERE company_id=? AND brand=? AND name=? AND is_rx=1 AND active=1').get(c,brand,name);if(!p){const rp=db.prepare('INSERT INTO products(company_id,brand,name,opening_stock,is_rx,active) VALUES(?,?,?,?,?,1)').run(c,brand,name,0,1);p=product(Number(rp.lastInsertRowid),c);}}else{p=validProduct(req.body,c);if(p.is_rx)throw Error('RX product cannot be used as FSV.');}const oldEffect=(old.order_type==='RX'||old.is_rx||old.status==='Cancelled')?0:old.quantity;const newEffect=(type==='RX'||status==='Cancelled')?0:q;for(const pid of new Set([old.product_id,p.id])){const x=product(pid,c);const projected=x.current_stock+(pid===old.product_id?oldEffect:0)-(pid===p.id?newEffect:0);if(projected<0)throw Error(`Insufficient stock for ${x.brand} — ${x.name}. Available: ${x.current_stock}.`);}const partyId=ensureParty(c,req.body.partyId,req.body.customerName,'Customer');const source=type==='RX'?[req.body.rxSource||'',req.body.notes||''].filter(Boolean).join(' | '):(req.body.notes||'');const newBill=String(req.body.billNumber||req.body.orderNumber||'').trim();if(old.bill_number&&newBill&&old.bill_number!==newBill){db.prepare('UPDATE payments SET bill_number=? WHERE company_id=? AND bill_number=?').run(newBill,c,old.bill_number);}db.prepare(`UPDATE orders SET order_number=?,shop_name=?,customer_name=?,party_id=?,product_id=?,quantity=?,unit_price=?,status=?,order_date=?,bill_number=?,bill_date=?,notes=?,order_type=? WHERE id=? AND company_id=?`).run(must(req.body.orderNumber,'Order number'),must(req.body.shopName,'Shop name'),must(req.body.customerName,'Customer name'),partyId,p.id,q,n(req.body.unitPrice||0,'Unit price'),status,req.body.orderDate||today(),newBill,req.body.billDate||req.body.orderDate||today(),source,type,old.id,c);return orderWithProduct(old.id,c)})));
app.delete('/api/orders/:id',http(req=>tx(()=>{const c=companyId(req),o=orderWithProduct(Number(req.params.id),c);if(!o)throw Error('Order not found.');if(o.bill_number){db.prepare('DELETE FROM payments WHERE company_id=? AND bill_number=?').run(c,o.bill_number);}db.prepare('DELETE FROM orders WHERE id=? AND company_id=?').run(o.id,c);return{ok:true}})));
app.post('/api/sales-returns',http(req=>tx(()=>{const c=companyId(req),p=validProduct(req.body,c),q=n(req.body.quantity,'Quantity',true),num=req.body.returnNumber||`SR-${Date.now()}`,cn=req.body.creditNoteNumber||`CN-${Date.now()}`;const r=db.prepare(`INSERT INTO sales_returns(company_id,return_number,bill_number,party_id,product_id,quantity,unit_price,return_date,credit_note_number,notes) VALUES(?,?,?,?,?,?,?,?,?,?)`).run(c,num,req.body.billNumber||'',req.body.partyId||null,p.id,q,n(req.body.unitPrice||0,'Unit price'),req.body.returnDate||today(),cn,req.body.notes||'');const amount=q*n(req.body.unitPrice||0,'Unit price');db.prepare(`INSERT OR IGNORE INTO credit_notes(company_id,credit_note_number,party_id,bill_number,amount,note_date,reason) VALUES(?,?,?,?,?,?,?)`).run(c,cn,req.body.partyId||null,req.body.billNumber||'',amount,req.body.returnDate||today(),'Sales Return');return db.prepare('SELECT sr.*,p.brand,p.name product_name FROM sales_returns sr JOIN products p ON p.id=sr.product_id WHERE sr.id=?').get(r.lastInsertRowid)})));
app.get('/api/sales-returns',http(req=>db.prepare(`SELECT sr.*,p.brand,p.name product_name,pa.name party_name FROM sales_returns sr JOIN products p ON p.id=sr.product_id LEFT JOIN parties pa ON pa.id=sr.party_id WHERE sr.company_id=? ORDER BY sr.return_date DESC,sr.id DESC`).all(companyId(req))));
app.put('/api/sales-returns/:id',http(req=>tx(()=>{const c=companyId(req),id=Number(req.params.id),old=db.prepare('SELECT * FROM sales_returns WHERE id=? AND company_id=?').get(id,c);if(!old)throw Error('Sales return not found.');const p=validProduct(req.body,c),q=n(req.body.quantity,'Quantity',true),price=n(req.body.unitPrice||0,'Unit price');const cn=must(req.body.creditNoteNumber||old.credit_note_number,'Credit note number');db.prepare('UPDATE sales_returns SET return_number=?,bill_number=?,party_id=?,product_id=?,quantity=?,unit_price=?,return_date=?,credit_note_number=?,notes=? WHERE id=? AND company_id=?').run(must(req.body.returnNumber,'Return number'),req.body.billNumber||'',req.body.partyId||null,p.id,q,price,req.body.returnDate||today(),cn,req.body.notes||'',id,c);if(old.credit_note_number && old.credit_note_number!==cn)db.prepare('DELETE FROM credit_notes WHERE company_id=? AND credit_note_number=?').run(c,old.credit_note_number);db.prepare('INSERT INTO credit_notes(company_id,credit_note_number,party_id,bill_number,amount,note_date,reason) VALUES(?,?,?,?,?,?,?) ON CONFLICT(company_id,credit_note_number) DO UPDATE SET party_id=excluded.party_id,bill_number=excluded.bill_number,amount=excluded.amount,note_date=excluded.note_date,reason=excluded.reason').run(c,cn,req.body.partyId||null,req.body.billNumber||'',q*price,req.body.returnDate||today(),'Sales Return');return db.prepare('SELECT sr.*,p.brand,p.name product_name,pa.name party_name FROM sales_returns sr JOIN products p ON p.id=sr.product_id LEFT JOIN parties pa ON pa.id=sr.party_id WHERE sr.id=? AND sr.company_id=?').get(id,c)})));
app.delete('/api/sales-returns/:id',http(req=>tx(()=>{const c=companyId(req),id=Number(req.params.id),sr=db.prepare('SELECT * FROM sales_returns WHERE id=? AND company_id=?').get(id,c);if(!sr)throw Error('Sales return not found.');if(sr.credit_note_number)db.prepare('DELETE FROM credit_notes WHERE company_id=? AND credit_note_number=?').run(c,sr.credit_note_number);db.prepare('DELETE FROM sales_returns WHERE id=? AND company_id=?').run(id,c);return{ok:true}})));
app.post('/api/foc',http(req=>tx(()=>{const c=companyId(req),p=validProduct(req.body,c),q=n(req.body.quantity,'Quantity',true);assertStock(p.id,c,-q);const r=db.prepare(`INSERT INTO foc_issues(company_id,foc_number,party_id,product_id,quantity,issue_date,notes) VALUES(?,?,?,?,?,?,?)`).run(c,req.body.focNumber||`FOC-${Date.now()}`,req.body.partyId||null,p.id,q,req.body.issueDate||today(),req.body.notes||'');return db.prepare(`SELECT f.*,p.brand,p.name product_name,pa.name party_name FROM foc_issues f JOIN products p ON p.id=f.product_id LEFT JOIN parties pa ON pa.id=f.party_id WHERE f.id=?`).get(r.lastInsertRowid)})));
app.get('/api/foc',http(req=>db.prepare(`SELECT f.*,p.brand,p.name product_name,pa.name party_name FROM foc_issues f JOIN products p ON p.id=f.product_id LEFT JOIN parties pa ON pa.id=f.party_id WHERE f.company_id=? ORDER BY f.issue_date DESC,f.id DESC`).all(companyId(req))));
app.put('/api/foc/:id',http(req=>tx(()=>{const c=companyId(req),id=Number(req.params.id),old=db.prepare('SELECT * FROM foc_issues WHERE id=? AND company_id=?').get(id,c);if(!old)throw Error('FOC record not found.');const p=validProduct(req.body,c),q=n(req.body.quantity,'Quantity',true);const oldEffect=old.quantity;const newEffect=q;for(const pid of new Set([old.product_id,p.id])){const x=product(pid,c);const projected=x.current_stock+(pid===old.product_id?oldEffect:0)-(pid===p.id?newEffect:0);if(projected<0)throw Error(`Insufficient stock for ${x.brand} — ${x.name}. Available: ${x.current_stock}.`);}db.prepare('UPDATE foc_issues SET foc_number=?,party_id=?,product_id=?,quantity=?,issue_date=?,notes=? WHERE id=? AND company_id=?').run(must(req.body.focNumber,'FOC number'),req.body.partyId||null,p.id,q,req.body.issueDate||today(),req.body.notes||'',id,c);return db.prepare('SELECT f.*,p.brand,p.name product_name,pa.name party_name FROM foc_issues f JOIN products p ON p.id=f.product_id LEFT JOIN parties pa ON pa.id=f.party_id WHERE f.id=? AND f.company_id=?').get(id,c)})));
app.delete('/api/foc/:id',http(req=>tx(()=>{const c=companyId(req),id=Number(req.params.id),f=db.prepare('SELECT * FROM foc_issues WHERE id=? AND company_id=?').get(id,c);if(!f)throw Error('FOC record not found.');db.prepare('DELETE FROM foc_issues WHERE id=? AND company_id=?').run(id,c);return{ok:true}})));
app.get('/api/parties',http(req=>db.prepare('SELECT * FROM parties WHERE company_id=? ORDER BY name').all(companyId(req))));
app.post('/api/parties',http(req=>{const c=companyId(req),r=db.prepare('INSERT INTO parties(company_id,name,type,phone,address,email,opening_balance) VALUES(?,?,?,?,?,?,?)').run(c,must(req.body.name,'Party name'),req.body.type||'Customer',req.body.phone||'',req.body.address||'',req.body.email||'',n(req.body.openingBalance||0,'Opening balance'));return db.prepare('SELECT * FROM parties WHERE id=?').get(r.lastInsertRowid)}));
app.get('/api/payments',http(req=>db.prepare(`SELECT py.*,pa.name party_name FROM payments py LEFT JOIN parties pa ON pa.id=py.party_id WHERE py.company_id=? ORDER BY py.payment_date DESC,py.id DESC`).all(companyId(req))));
app.put('/api/payments/:id',http(req=>tx(()=>{const c=companyId(req),id=Number(req.params.id),py=db.prepare('SELECT * FROM payments WHERE id=? AND company_id=?').get(id,c);if(!py)throw Error('Payment not found.');const amount=n(req.body.amount,'Amount',true),type=String(req.body.paymentType||py.payment_type);if(!['Received','Paid'].includes(type))throw Error('Invalid payment type.');db.prepare('UPDATE payments SET party_id=?,payment_type=?,amount=?,payment_date=?,bill_number=?,reference=?,notes=? WHERE id=? AND company_id=?').run(req.body.partyId||null,type,amount,req.body.paymentDate||today(),req.body.billNumber||'',req.body.reference||'',req.body.notes||'',id,c);return db.prepare('SELECT py.*,pa.name party_name FROM payments py LEFT JOIN parties pa ON pa.id=py.party_id WHERE py.id=? AND py.company_id=?').get(id,c)})));
app.delete('/api/payments/:id',http(req=>tx(()=>{const c=companyId(req),id=Number(req.params.id);const py=db.prepare('SELECT id FROM payments WHERE id=? AND company_id=?').get(id,c);if(!py)throw Error('Payment not found.');db.prepare('DELETE FROM payments WHERE id=? AND company_id=?').run(id,c);return{ok:true}})));
app.post('/api/payments',http(req=>tx(()=>{const c=companyId(req),amount=n(req.body.amount,'Amount',true),party=req.body.partyId?db.prepare('SELECT id FROM parties WHERE id=? AND company_id=?').get(Number(req.body.partyId),c):null;if(req.body.partyId&&!party)throw Error('Select a valid party.');const r=db.prepare(`INSERT INTO payments(company_id,party_id,payment_type,amount,payment_date,bill_number,reference,notes) VALUES(?,?,?,?,?,?,?,?)`).run(c,party?.id||null,req.body.paymentType||'Received',amount,req.body.paymentDate||today(),req.body.billNumber||'',req.body.reference||'',req.body.notes||'');return db.prepare('SELECT py.*,pa.name party_name FROM payments py LEFT JOIN parties pa ON pa.id=py.party_id WHERE py.id=?').get(r.lastInsertRowid)})));
app.get('/api/financing',http(req=>{const c=companyId(req);return db.prepare(`SELECT o.id,o.customer_name party_name,o.bill_number,o.bill_date,o.unit_price*o.quantity total_amount,o.status FROM orders o WHERE o.company_id=? AND o.status<>'Cancelled' ORDER BY o.bill_date DESC,o.id DESC`).all(c)}));
app.get('/api/ledger',http(req=>{const c=companyId(req);return db.prepare(`SELECT pa.id,pa.name,pa.opening_balance,
COALESCE((SELECT SUM(o.quantity*o.unit_price) FROM orders o WHERE o.company_id=pa.company_id AND o.party_id=pa.id AND o.status<>'Cancelled'),0) sales,
COALESCE((SELECT SUM(sr.quantity*sr.unit_price) FROM sales_returns sr WHERE sr.company_id=pa.company_id AND sr.party_id=pa.id),0) returns,
COALESCE((SELECT SUM(py.amount) FROM payments py WHERE py.company_id=pa.company_id AND py.party_id=pa.id AND py.payment_type='Received'),0) received,
COALESCE((SELECT SUM(py.amount) FROM payments py WHERE py.company_id=pa.company_id AND py.party_id=pa.id AND py.payment_type='Paid'),0) paid
FROM parties pa WHERE pa.company_id=? ORDER BY pa.name`).all(c)}));
app.get('/api/ledger/:partyId',http(req=>{const c=companyId(req),pid=Number(req.params.partyId),party=db.prepare('SELECT * FROM parties WHERE id=? AND company_id=?').get(pid,c);if(!party)throw Error('Party not found.');const from=req.query.from||'0000-01-01',to=req.query.to||'9999-12-31';const rows=[];db.prepare(`SELECT o.id,o.order_date date,'Sales Invoice' type,o.bill_number ref,o.quantity qty,o.quantity*o.unit_price debit,o.status,o.order_type FROM orders o WHERE o.company_id=? AND o.party_id=? AND o.status<>'Cancelled' AND o.order_date BETWEEN ? AND ? ORDER BY o.order_date,o.id`).all(c,pid,from,to).forEach(x=>rows.push(x));db.prepare(`SELECT sr.id,sr.return_date date,'Credit Note / Return' type,sr.credit_note_number ref,sr.quantity qty,0 debit,-sr.quantity*sr.unit_price credit FROM sales_returns sr WHERE sr.company_id=? AND sr.party_id=? AND sr.return_date BETWEEN ? AND ? ORDER BY sr.return_date,sr.id`).all(c,pid,from,to).forEach(x=>rows.push(x));db.prepare(`SELECT py.id,py.payment_date date,'Payment - '+py.payment_type type,COALESCE(py.reference,py.bill_number,'') ref,0 qty,CASE WHEN py.payment_type='Paid' THEN py.amount ELSE 0 END debit,CASE WHEN py.payment_type='Received' THEN py.amount ELSE 0 END credit FROM payments py WHERE py.company_id=? AND py.party_id=? AND py.payment_date BETWEEN ? AND ? ORDER BY py.payment_date,py.id`).all(c,pid,from,to).forEach(x=>rows.push(x));rows.sort((a,b)=>String(a.date).localeCompare(String(b.date))||a.id-b.id);let bal=Number(party.opening_balance||0);rows.forEach(x=>{bal+=Number(x.debit||0)-Number(x.credit||0);x.balance=bal});return{party,rows,balance:bal}}));
app.get('/api/reports',http(req=>{const c=companyId(req),type=String(req.query.type||'inventory').toLowerCase(),from=req.query.from||'0000-01-01',to=req.query.to||'9999-12-31',pid=req.query.partyId?Number(req.query.partyId):null;if(type==='ledger'){if(!pid)throw Error('Select a party for Ledger report.');return db.prepare(`SELECT * FROM (SELECT o.order_date date,'Sales Invoice' type,o.bill_number reference,o.quantity,o.quantity*o.unit_price amount,o.party_id FROM orders o WHERE o.company_id=? AND o.party_id=? AND o.status<>'Cancelled' UNION ALL SELECT sr.return_date,'Credit Note',sr.credit_note_number,sr.quantity,-sr.quantity*sr.unit_price,sr.party_id FROM sales_returns sr WHERE sr.company_id=? AND sr.party_id=? UNION ALL SELECT py.payment_date,'Payment - '||py.payment_type,COALESCE(py.reference,py.bill_number,''),0,CASE WHEN py.payment_type='Received' THEN -py.amount ELSE py.amount END,py.party_id FROM payments py WHERE py.company_id=? AND py.party_id=?) WHERE date BETWEEN ? AND ? ORDER BY date`).all(c,pid,c,pid,c,pid,from,to)}if(type==='inventory')return products(c);if(type==='sales')return listOrders(c).filter(x=>x.order_date>=from&&x.order_date<=to&&(pid?x.party_id===pid:true));if(type==='purchases')return listPurchases(c).filter(x=>x.purchase_date>=from&&x.purchase_date<=to);if(type==='payments')return db.prepare(`SELECT py.*,pa.name party_name FROM payments py LEFT JOIN parties pa ON pa.id=py.party_id WHERE py.company_id=? AND py.payment_date BETWEEN ? AND ? ${pid?'AND py.party_id=?':''} ORDER BY py.payment_date DESC,py.id DESC`).all(...(pid?[c,from,to,pid]:[c,from,to]));if(type==='returns'){const sql=`SELECT sr.*,pa.name party_name,p.name product_name FROM sales_returns sr LEFT JOIN parties pa ON pa.id=sr.party_id JOIN products p ON p.id=sr.product_id WHERE sr.company_id=? AND sr.return_date BETWEEN ? AND ? ${pid?'AND sr.party_id=?':''} ORDER BY sr.return_date DESC`;return db.prepare(sql).all(...(pid?[c,from,to,pid]:[c,from,to]));}if(type==='foc'){const sql=`SELECT f.*,pa.name party_name,p.name product_name FROM foc_issues f LEFT JOIN parties pa ON pa.id=f.party_id JOIN products p ON p.id=f.product_id WHERE f.company_id=? AND f.issue_date BETWEEN ? AND ? ${pid?'AND f.party_id=?':''} ORDER BY f.issue_date DESC`;return db.prepare(sql).all(...(pid?[c,from,to,pid]:[c,from,to]));}return listOrders(c).filter(x=>x.order_date>=from&&x.order_date<=to)}));
app.get('/api/users',http(req=>db.prepare('SELECT id,username,display_name,role,active FROM users WHERE company_id=? ORDER BY username').all(companyId(req))));
app.post('/api/users',http(req=>tx(()=>{const c=companyId(req),r=db.prepare('INSERT INTO users(company_id,username,password,display_name,role) VALUES(?,?,?,?,?)').run(c,must(req.body.username,'Username'),must(req.body.password,'Password'),must(req.body.displayName,'Display name'),req.body.role||'User');const mods=req.body.permissions||{};for(const [m,a] of Object.entries(mods))db.prepare('INSERT INTO user_permissions(user_id,module,allowed) VALUES(?,?,?)').run(r.lastInsertRowid,m,a?1:0);return db.prepare('SELECT id,username,display_name,role,active FROM users WHERE id=?').get(r.lastInsertRowid)})));
app.get('/api/users/:id/permissions',http(req=>db.prepare('SELECT module,allowed FROM user_permissions WHERE user_id=?').all(Number(req.params.id))));
app.put('/api/users/:id/permissions',http(req=>tx(()=>{const id=Number(req.params.id);for(const [m,a] of Object.entries(req.body.permissions||{}))db.prepare('INSERT INTO user_permissions(user_id,module,allowed) VALUES(?,?,?) ON CONFLICT(user_id,module) DO UPDATE SET allowed=excluded.allowed').run(id,m,a?1:0);return{ok:true}})));
app.post('/api/login',http(req=>{const c=Number(req.body.companyId||shivaayId),u=db.prepare('SELECT id,username,password,display_name,role FROM users WHERE company_id=? AND username=? AND active=1').get(c,must(req.body.username,'Username'));if(!u||u.password!==String(req.body.password||''))throw Error('Invalid username or password.');const permissions=db.prepare('SELECT module,allowed FROM user_permissions WHERE user_id=?').all(u.id).reduce((a,x)=>(a[x.module]=!!x.allowed,a),{});return{user:{id:u.id,username:u.username,displayName:u.display_name,role:u.role},permissions}}));
function exportRows(kind,c){if(kind==='inventory')return products(c).map(p=>({Brand:p.brand,Product:p.name,'Opening Stock':p.opening_stock,RX:p.is_rx?'Yes':'No',Purchases:p.purchased,Sales:p.sold,'Sales Returns':p.returned,FOC:p.foc,'Current Stock':p.current_stock}));if(kind==='orders')return listOrders(c).map(o=>({'Order Number':o.order_number,'Order Type':o.order_type||'FSV','Shop Name':o.shop_name,'Customer Name':o.customer_name,Brand:o.brand,Product:o.product_name,Quantity:o.quantity,'Unit Price':o.unit_price,Status:o.status,Date:o.order_date,'Bill Number':o.bill_number,'Bill Date':o.bill_date}));if(kind==='purchases')return listPurchases(c).map(p=>({Brand:p.brand,Product:p.product_name,Quantity:p.quantity,Supplier:p.supplier,Reference:p.reference,Date:p.purchase_date,Notes:p.notes}));if(kind==='parties')return db.prepare('SELECT name as Name,type as Type,phone as Phone,address as Address,email as Email,opening_balance as OpeningBalance FROM parties WHERE company_id=?').all(c);if(kind==='payments')return db.prepare('SELECT payment_type as Type,amount as Amount,payment_date as Date,bill_number as BillNumber,reference as Reference,notes as Notes FROM payments WHERE company_id=?').all(c);if(kind==='returns')return db.prepare('SELECT return_number as ReturnNumber,bill_number as BillNumber,quantity as Quantity,unit_price as UnitPrice,return_date as Date,credit_note_number as CreditNoteNumber FROM sales_returns WHERE company_id=?').all(c);return[]}
app.get('/api/export/:kind',http(req=>{const c=companyId(req),kind=req.params.kind,allowed=['inventory','orders','purchases','parties','payments','returns'];if(!allowed.includes(kind))throw Error('Unsupported export type.');return{kind,rows:exportRows(kind,c)}}));
// Binary download route is separate so the frontend can create an actual .xlsx file.
app.get('/api/export-xlsx/:kind',(req,res)=>{try{const c=companyId(req),kind=req.params.kind,rows=exportRows(kind,c);const ws=XLSX.utils.json_to_sheet(rows),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,kind);const out=XLSX.write(wb,{type:'buffer',bookType:'xlsx'});res.type('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet').attachment(`${kind}.xlsx`).send(out)}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/import/:kind',upload.single('file'),http(req=>tx(()=>{if(!req.file)throw Error('Choose an Excel file.');const c=companyId(req),kind=req.params.kind,book=XLSX.read(req.file.buffer,{type:'buffer'}),rows=XLSX.utils.sheet_to_json(book.Sheets[book.SheetNames[0]],{defval:''});const get=(r,...ks)=>{for(const k of ks)if(r[k]!==undefined)return r[k];return''};let count=0;for(const r of rows){if(kind==='inventory'){const brand=must(get(r,'Brand'),'Brand'),name=must(get(r,'Product'),'Product'),opening=n(get(r,'Opening Stock','OpeningStock')||0,'Opening stock'),rx=String(get(r,'RX')).toLowerCase()==='yes';const old=db.prepare('SELECT id FROM products WHERE company_id=? AND brand=? AND name=?').get(c,brand,name);old?db.prepare('UPDATE products SET opening_stock=?,is_rx=? WHERE id=?').run(opening,rx?1:0,old.id):db.prepare('INSERT INTO products(company_id,brand,name,opening_stock,is_rx) VALUES(?,?,?,?,?)').run(c,brand,name,opening,rx?1:0);count++}else if(kind==='parties'){db.prepare('INSERT INTO parties(company_id,name,type,phone,address,email,opening_balance) VALUES(?,?,?,?,?,?,?) ON CONFLICT(company_id,name) DO UPDATE SET type=excluded.type,phone=excluded.phone,address=excluded.address,email=excluded.email,opening_balance=excluded.opening_balance').run(c,must(get(r,'Name','name'),'Name'),get(r,'Type','type')||'Customer',get(r,'Phone','phone'),get(r,'Address','address'),get(r,'Email','email'),n(get(r,'OpeningBalance','Opening Balance')||0,'Opening balance'));count++}else throw Error(`Import template for ${kind} is not enabled yet.`)}return{ok:true,imported:count}})));
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'index.html')));
if(require.main===module)app.listen(process.env.PORT||3000,()=>console.log('Sangam Nexus running on http://localhost:3000'));
module.exports=app;
